version: '3.8'

services:
  odoo:
    image: odoo:17.0
    container_name: odoo
    restart: unless-stopped
    ports:
      - "8069:8069"
    environment:
      - ODOO_DB=odoo
      - ODOO_USER=admin
      - ODOO_PASSWORD=admin
    depends_on:
      - db
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons

  db:
    image: postgres:15
    container_name: odoo-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  odoo-data:
  db-data:
